-- H2 2.3.232;
;             
CREATE USER IF NOT EXISTS "SA" SALT '72e62b1241f7626d' HASH '9fb0c1a47fd56593e8c615e88f146fff8954e0b096218e1abb9ae9236d22e57f' ADMIN;         
CREATE CACHED TABLE "PUBLIC"."PRODUCT"(
    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 41) NOT NULL,
    "CODE" CHARACTER(15),
    "NAME" CHARACTER VARYING,
    "PRICE_EUR" INTEGER,
    "PRICE_USD" INTEGER,
    "DESCRIPTION" CHARACTER VARYING
);     
-- 8 +/- SELECT COUNT(*) FROM PUBLIC.PRODUCT; 
INSERT INTO "PUBLIC"."PRODUCT" VALUES
(1, '000120000124554', 'The Mulchesters', 30, 70, 'ahc a'),
(2, '534686111241576', 'Hamburgers', 7, 14, 'ahc a'),
(3, '454987696323159', 'Tacos', 3, 5, 'Cest un bon taco'),
(39, '123451234512345', 'ja', 200, 227, 'opo'),
(40, 'abcdefabcdefghi', 'jac', 60, 68, 'naccca'),
(100, 'HX0000625478ac3', 'Samsung Galaxy S23', 25, 65, 'Questo e un belissimo prodotto, un telefonino da Samsung'),
(200, 'HX0000625478ac4', 'iPhone SE', 35, 40, 'iPhone13 - like iPhone 12 but more expensive'),
(300, 'HX0000625478ac5', 'Xiaomi 13', 90, 120, 'Xiami 13 brings you the best of the best');   
CREATE CACHED TABLE "PUBLIC"."REVIEW"(
    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 69) NOT NULL,
    "PRODUCT_ID" INTEGER,
    "REVIEWER" CHARACTER VARYING,
    "TEXT" CHARACTER VARYING,
    "RATING" ENUM('1', '2', '3', '4', '5')
);
ALTER TABLE "PUBLIC"."REVIEW" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8" PRIMARY KEY("ID");       
-- 6 +/- SELECT COUNT(*) FROM PUBLIC.REVIEW;  
INSERT INTO "PUBLIC"."REVIEW" VALUES
(1, 2, 'ohja', 'to je dobar stek', '1'),
(2, 3, 'ah', 'nije lose ali moze bolje', '3'),
(34, 39, 'ah', 'nijelos', '5'),
(35, 39, 'aja', 'oho', '4'),
(36, 39, 'The man', 'tko hoce ovo, alo', '1'),
(68, 40, 'acha', 'nok', '5');  
ALTER TABLE "PUBLIC"."PRODUCT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1" UNIQUE NULLS DISTINCT ("CODE");         
